[package]
name = "galactic_client"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
bevy = {git = "https://github.com/bevyengine/bevy.git", commit = "1d0d8a3397bd6fc2c14d42ffd0668d2443748912"}
renet_udp = {git = "https://github.com/lucaspoffo/renet", commit = "350f82bbeae51cd07edafe82eea47deb453c14bf"}

# serde = { version = "1.0.117", features = [ "derive" ] } 
# bincode = "1.3.1"
# log = { version = "0.4.11", features = [ "std" ] }

galactic_core = {path = "../core"}

[profile.dev.package."*"]
opt-level = 3
