[package]
name = "galactic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
bevy = {git = "https://github.com/bevyengine/bevy.git"}
bevy-remote-devtools-plugin = { git = "https://github.com/reneeichhorn/bevy-remote-devtools.git" }

[patch.crates-io]
hyper = { git = "https://github.com/reneeichhorn/hyper.git" }